services:
  - type: web
    name: ai-resume-optimizer
    runtime: python
    runtimeVersion: 3.11.9
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: FLASK_SECRET_KEY
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: LEMONSQUEEZY_API_KEY
        sync: false
      - key: LEMONSQUEEZY_STORE_ID
        sync: false
      - key: LEMONSQUEEZY_VARIANT_ID
        sync: false
      - key: LEMONSQUEEZY_WEBHOOK_SECRET
        sync: false
